name: tests

on:
  [push]

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ~1.15
    - uses: actions/checkout@v2
    - run: make build
    - run: git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ~1.15
    - uses: actions/checkout@v2
    - run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
